"""parserモジュールのテスト."""

import tempfile
from pathlib import Path

from news_youtube.parser import (
    DailyDigest,
    NewsStory,
    _clean_text,
    _extract_date,
    _format_date_japanese,
    parse_owlclaw_daily,
    to_speech_script,
)

SAMPLE_MARKDOWN = """\
---
date: 2026-06-11
source: owlclaw
tags: [ai-digest]
---

# AI Digest — 2026-06-11

## Top Stories

### 1. テスト記事タイトル1
- **Source**: TechCrunch AI
- **Link**: https://example.com/1
- **Summary**:
  テスト記事の概要テキスト。AIに関する重要なニュース。
- **Why it matters**: これが重要な理由を説明するテキスト。

### 2. テスト記事タイトル2
- **Source**: SaaStr
- **Link**: https://example.com/2
- **Summary**:
  2番目の記事の概要テキスト。SaaS関連のニュース。
- **Why it matters**: SaaS企業にとって参考になる示唆がある。

---
*Generated by owlclaw*
"""


class TestExtractDate:
    """日付抽出のテスト."""

    def test_frontmatter_date(self) -> None:
        text = "---\ndate: 2026-06-11\n---\n# Title"
        assert _extract_date(text) == "2026-06-11"

    def test_unknown_date(self) -> None:
        text = "# No date here"
        assert _extract_date(text) == "unknown"


class TestCleanText:
    """テキストクリーニングのテスト."""

    def test_bold_removal(self) -> None:
        assert _clean_text("**太字**テキスト") == "太字テキスト"

    def test_link_removal(self) -> None:
        assert _clean_text("[リンク](https://example.com)") == "リンク"

    def test_whitespace_normalization(self) -> None:
        assert _clean_text("  複数の   空白  ") == "複数の 空白"


class TestParseOwlclawDaily:
    """Markdownパーサーの統合テスト."""

    def test_parse_sample(self) -> None:
        with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False, encoding="utf-8") as f:
            f.write(SAMPLE_MARKDOWN)
            f.flush()
            digest = parse_owlclaw_daily(f.name)

        assert digest.date == "2026-06-11"
        expected_story_count = 2
        assert len(digest.stories) == expected_story_count
        assert digest.stories[0].number == 1
        assert digest.stories[0].title == "テスト記事タイトル1"
        assert digest.stories[0].source == "TechCrunch AI"
        assert "AI" in digest.stories[0].summary
        assert digest.stories[1].number == expected_story_count

        Path(f.name).unlink()


class TestToSpeechScript:
    """音声スクリプト変換のテスト."""

    def test_script_structure(self) -> None:
        digest = DailyDigest(
            date="2026-06-11",
            stories=[
                NewsStory(
                    number=1,
                    title="テストタイトル",
                    source="テストソース",
                    summary="テスト概要",
                    why_it_matters="テスト重要性",
                ),
            ],
        )
        script = to_speech_script(digest)
        assert "owlclaw AIダイジェスト" in script
        assert "2026年6月11日" in script
        assert "第1位" in script
        assert "テストタイトル" in script
        assert "テスト概要" in script


class TestFormatDateJapanese:
    """日本語日付フォーマットのテスト."""

    def test_normal_date(self) -> None:
        assert _format_date_japanese("2026-06-11") == "2026年6月11日"

    def test_invalid_date(self) -> None:
        assert _format_date_japanese("invalid") == "invalid"
